tracer:
  property: "I AM THE DEFAULT"

spring:
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    platform: postgres
    username: licensingservice
    url: "jdbc:postgresql://database:5432/eagle_eye"
    password: "{cipher}3a3d0af393a67834cc3db532e7e4d0e1ffa954861ae5affc87d2ae2d768a04e4"
    test-while-idle: true
    validation-query: "SELECT 1"
  jpa:
    url: "jdbc:postgresql://database:5432/eagle_eye"
    database: POSTGRESQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: validate
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true