tracer.property: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform: "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye"
spring.datasource.username: "licensingservice"
spring.datasource.password: "{cipher} 8bcd6a0126e32787d4e2e45c7b9b8e8e233fda0c0f6c250f29c335fa5ae7aefe"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"